version: '2'

services:
  dwx17.workshop.webapp:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

#  dwx17.workshop.cli:
#    build:
#      args:
#        source: ${DOCKER_BUILD_SOURCE}
#    volumes:
#      - ~/clrdbg:/clrdbg:ro
#    entrypoint: tail -f /dev/null
#    labels:
#      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
